/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppBotRouteImport } from './routes/_authed/_app/bot'
import { Route as AuthedAppRoutinesRouteImport } from './routes/_authed/_app/routines'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsBillingRouteImport } from './routes/_authed/settings/billing'
import { Route as AuthedSettingsBoundariesRouteImport } from './routes/_authed/settings/boundaries'
import { Route as AuthedSettingsComputerRouteImport } from './routes/_authed/settings/computer'
import { Route as AuthedSettingsMemoryRouteImport } from './routes/_authed/settings/memory'
import { Route as AuthedSettingsSchedulesRouteImport } from './routes/_authed/settings/schedules'
import { Route as AuthedSettingsTasksRouteImport } from './routes/_authed/settings/tasks'
import { Route as AuthedSettingsTelegramRouteImport } from './routes/_authed/settings/telegram'
import { Route as AuthedSettingsVaultRouteImport } from './routes/_authed/settings/vault'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppAppsIndexRouteImport } from './routes/_authed/_app/apps/index'
import { Route as AuthedAppAppsKeyRouteImport } from './routes/_authed/_app/apps/$key'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'
import { Route as AuthedSettingsComponentsGalleryIndexRouteImport } from './routes/_authed/settings/components-gallery/index'
import { Route as AuthedSettingsComponentsGalleryNameRouteImport } from './routes/_authed/settings/components-gallery/$name'
import { Route as AuthedSettingsConnectedAccountsIndexRouteImport } from './routes/_authed/settings/connected-accounts/index'
import { Route as AuthedSettingsConnectedAccountsKeyRouteImport } from './routes/_authed/settings/connected-accounts/$key'
import { Route as AuthedSettingsFilesIndexRouteImport } from './routes/_authed/settings/files/index'
import { Route as AuthedSettingsFilesIdRouteImport } from './routes/_authed/settings/files/$id'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotRoute = AuthedAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppRoutinesRoute = AuthedAppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsBillingRoute = AuthedSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsBoundariesRoute =
  AuthedSettingsBoundariesRouteImport.update({
    id: '/boundaries',
    path: '/boundaries',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsComputerRoute = AuthedSettingsComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsMemoryRoute = AuthedSettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsSchedulesRoute = AuthedSettingsSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsTasksRoute = AuthedSettingsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsTelegramRoute = AuthedSettingsTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedSettingsVaultRoute = AuthedSettingsVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAppsIndexRoute = AuthedAppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppAppsKeyRoute = AuthedAppAppsKeyRouteImport.update({
  id: '/apps/$key',
  path: '/apps/$key',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedSettingsComponentsGalleryIndexRoute =
  AuthedSettingsComponentsGalleryIndexRouteImport.update({
    id: '/components-gallery/',
    path: '/components-gallery/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsComponentsGalleryNameRoute =
  AuthedSettingsComponentsGalleryNameRouteImport.update({
    id: '/components-gallery/$name',
    path: '/components-gallery/$name',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsIndexRoute =
  AuthedSettingsConnectedAccountsIndexRouteImport.update({
    id: '/connected-accounts/',
    path: '/connected-accounts/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsKeyRoute =
  AuthedSettingsConnectedAccountsKeyRouteImport.update({
    id: '/connected-accounts/$key',
    path: '/connected-accounts/$key',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsFilesIndexRoute =
  AuthedSettingsFilesIndexRouteImport.update({
    id: '/files/',
    path: '/files/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsFilesIdRoute = AuthedSettingsFilesIdRouteImport.update({
  id: '/files/$id',
  path: '/files/$id',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/onboarding': typeof AuthedOnboardingRoute
  '/bot': typeof AuthedAppBotRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/settings/boundaries': typeof AuthedSettingsBoundariesRoute
  '/settings/computer': typeof AuthedSettingsComputerRoute
  '/settings/memory': typeof AuthedSettingsMemoryRoute
  '/settings/schedules': typeof AuthedSettingsSchedulesRoute
  '/settings/tasks': typeof AuthedSettingsTasksRoute
  '/settings/telegram': typeof AuthedSettingsTelegramRoute
  '/settings/vault': typeof AuthedSettingsVaultRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/apps/$key': typeof AuthedAppAppsKeyRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/settings/files/$id': typeof AuthedSettingsFilesIdRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
  '/apps/': typeof AuthedAppAppsIndexRoute
  '/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/settings/files/': typeof AuthedSettingsFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/bot': typeof AuthedAppBotRoute
  '/routines': typeof AuthedAppRoutinesRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/settings/billing': typeof AuthedSettingsBillingRoute
  '/settings/boundaries': typeof AuthedSettingsBoundariesRoute
  '/settings/computer': typeof AuthedSettingsComputerRoute
  '/settings/memory': typeof AuthedSettingsMemoryRoute
  '/settings/schedules': typeof AuthedSettingsSchedulesRoute
  '/settings/tasks': typeof AuthedSettingsTasksRoute
  '/settings/telegram': typeof AuthedSettingsTelegramRoute
  '/settings/vault': typeof AuthedSettingsVaultRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/apps/$key': typeof AuthedAppAppsKeyRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/settings/files/$id': typeof AuthedSettingsFilesIdRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
  '/apps': typeof AuthedAppAppsIndexRoute
  '/settings/components-gallery': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/settings/files': typeof AuthedSettingsFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/_app/bot': typeof AuthedAppBotRoute
  '/_authed/_app/routines': typeof AuthedAppRoutinesRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/settings/billing': typeof AuthedSettingsBillingRoute
  '/_authed/settings/boundaries': typeof AuthedSettingsBoundariesRoute
  '/_authed/settings/computer': typeof AuthedSettingsComputerRoute
  '/_authed/settings/memory': typeof AuthedSettingsMemoryRoute
  '/_authed/settings/schedules': typeof AuthedSettingsSchedulesRoute
  '/_authed/settings/tasks': typeof AuthedSettingsTasksRoute
  '/_authed/settings/telegram': typeof AuthedSettingsTelegramRoute
  '/_authed/settings/vault': typeof AuthedSettingsVaultRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_app/apps/$key': typeof AuthedAppAppsKeyRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/_authed/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/_authed/settings/files/$id': typeof AuthedSettingsFilesIdRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
  '/_authed/_app/apps/': typeof AuthedAppAppsIndexRoute
  '/_authed/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/_authed/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/_authed/settings/files/': typeof AuthedSettingsFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/settings'
    | '/onboarding'
    | '/bot'
    | '/routines'
    | '/skills'
    | '/settings/billing'
    | '/settings/boundaries'
    | '/settings/computer'
    | '/settings/memory'
    | '/settings/schedules'
    | '/settings/tasks'
    | '/settings/telegram'
    | '/settings/vault'
    | '/settings/'
    | '/apps/$key'
    | '/channel/$channelId'
    | '/channel/new'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/settings/files/$id'
    | '/agents/'
    | '/apps/'
    | '/settings/components-gallery/'
    | '/settings/connected-accounts/'
    | '/settings/files/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/onboarding'
    | '/bot'
    | '/routines'
    | '/skills'
    | '/settings/billing'
    | '/settings/boundaries'
    | '/settings/computer'
    | '/settings/memory'
    | '/settings/schedules'
    | '/settings/tasks'
    | '/settings/telegram'
    | '/settings/vault'
    | '/settings'
    | '/apps/$key'
    | '/channel/$channelId'
    | '/channel/new'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/settings/files/$id'
    | '/agents'
    | '/apps'
    | '/settings/components-gallery'
    | '/settings/connected-accounts'
    | '/settings/files'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/settings'
    | '/_authed/_app'
    | '/_authed/onboarding'
    | '/_authed/_app/bot'
    | '/_authed/_app/routines'
    | '/_authed/_app/skills'
    | '/_authed/settings/billing'
    | '/_authed/settings/boundaries'
    | '/_authed/settings/computer'
    | '/_authed/settings/memory'
    | '/_authed/settings/schedules'
    | '/_authed/settings/tasks'
    | '/_authed/settings/telegram'
    | '/_authed/settings/vault'
    | '/_authed/_app/'
    | '/_authed/settings/'
    | '/_authed/_app/apps/$key'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/settings/components-gallery/$name'
    | '/_authed/settings/connected-accounts/$key'
    | '/_authed/settings/files/$id'
    | '/_authed/_app/agents/'
    | '/_authed/_app/apps/'
    | '/_authed/settings/components-gallery/'
    | '/_authed/settings/connected-accounts/'
    | '/_authed/settings/files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bot': {
      id: '/_authed/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedAppBotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/routines': {
      id: '/_authed/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AuthedAppRoutinesRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/billing': {
      id: '/_authed/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthedSettingsBillingRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/boundaries': {
      id: '/_authed/settings/boundaries'
      path: '/boundaries'
      fullPath: '/settings/boundaries'
      preLoaderRoute: typeof AuthedSettingsBoundariesRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/computer': {
      id: '/_authed/settings/computer'
      path: '/computer'
      fullPath: '/settings/computer'
      preLoaderRoute: typeof AuthedSettingsComputerRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/memory': {
      id: '/_authed/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof AuthedSettingsMemoryRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/schedules': {
      id: '/_authed/settings/schedules'
      path: '/schedules'
      fullPath: '/settings/schedules'
      preLoaderRoute: typeof AuthedSettingsSchedulesRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/tasks': {
      id: '/_authed/settings/tasks'
      path: '/tasks'
      fullPath: '/settings/tasks'
      preLoaderRoute: typeof AuthedSettingsTasksRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/telegram': {
      id: '/_authed/settings/telegram'
      path: '/telegram'
      fullPath: '/settings/telegram'
      preLoaderRoute: typeof AuthedSettingsTelegramRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/vault': {
      id: '/_authed/settings/vault'
      path: '/vault'
      fullPath: '/settings/vault'
      preLoaderRoute: typeof AuthedSettingsVaultRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/apps/': {
      id: '/_authed/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthedAppAppsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/apps/$key': {
      id: '/_authed/_app/apps/$key'
      path: '/apps/$key'
      fullPath: '/apps/$key'
      preLoaderRoute: typeof AuthedAppAppsKeyRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/settings/components-gallery/': {
      id: '/_authed/settings/components-gallery/'
      path: '/components-gallery'
      fullPath: '/settings/components-gallery/'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/components-gallery/$name': {
      id: '/_authed/settings/components-gallery/$name'
      path: '/components-gallery/$name'
      fullPath: '/settings/components-gallery/$name'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryNameRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/': {
      id: '/_authed/settings/connected-accounts/'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts/'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/$key': {
      id: '/_authed/settings/connected-accounts/$key'
      path: '/connected-accounts/$key'
      fullPath: '/settings/connected-accounts/$key'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsKeyRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/files/': {
      id: '/_authed/settings/files/'
      path: '/files'
      fullPath: '/settings/files/'
      preLoaderRoute: typeof AuthedSettingsFilesIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/files/$id': {
      id: '/_authed/settings/files/$id'
      path: '/files/$id'
      fullPath: '/settings/files/$id'
      preLoaderRoute: typeof AuthedSettingsFilesIdRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
  }
}

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsBillingRoute: typeof AuthedSettingsBillingRoute
  AuthedSettingsBoundariesRoute: typeof AuthedSettingsBoundariesRoute
  AuthedSettingsComputerRoute: typeof AuthedSettingsComputerRoute
  AuthedSettingsMemoryRoute: typeof AuthedSettingsMemoryRoute
  AuthedSettingsSchedulesRoute: typeof AuthedSettingsSchedulesRoute
  AuthedSettingsTasksRoute: typeof AuthedSettingsTasksRoute
  AuthedSettingsTelegramRoute: typeof AuthedSettingsTelegramRoute
  AuthedSettingsVaultRoute: typeof AuthedSettingsVaultRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsComponentsGalleryNameRoute: typeof AuthedSettingsComponentsGalleryNameRoute
  AuthedSettingsConnectedAccountsKeyRoute: typeof AuthedSettingsConnectedAccountsKeyRoute
  AuthedSettingsFilesIdRoute: typeof AuthedSettingsFilesIdRoute
  AuthedSettingsComponentsGalleryIndexRoute: typeof AuthedSettingsComponentsGalleryIndexRoute
  AuthedSettingsConnectedAccountsIndexRoute: typeof AuthedSettingsConnectedAccountsIndexRoute
  AuthedSettingsFilesIndexRoute: typeof AuthedSettingsFilesIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsBillingRoute: AuthedSettingsBillingRoute,
  AuthedSettingsBoundariesRoute: AuthedSettingsBoundariesRoute,
  AuthedSettingsComputerRoute: AuthedSettingsComputerRoute,
  AuthedSettingsMemoryRoute: AuthedSettingsMemoryRoute,
  AuthedSettingsSchedulesRoute: AuthedSettingsSchedulesRoute,
  AuthedSettingsTasksRoute: AuthedSettingsTasksRoute,
  AuthedSettingsTelegramRoute: AuthedSettingsTelegramRoute,
  AuthedSettingsVaultRoute: AuthedSettingsVaultRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsComponentsGalleryNameRoute:
    AuthedSettingsComponentsGalleryNameRoute,
  AuthedSettingsConnectedAccountsKeyRoute:
    AuthedSettingsConnectedAccountsKeyRoute,
  AuthedSettingsFilesIdRoute: AuthedSettingsFilesIdRoute,
  AuthedSettingsComponentsGalleryIndexRoute:
    AuthedSettingsComponentsGalleryIndexRoute,
  AuthedSettingsConnectedAccountsIndexRoute:
    AuthedSettingsConnectedAccountsIndexRoute,
  AuthedSettingsFilesIndexRoute: AuthedSettingsFilesIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedAppRouteChildren {
  AuthedAppBotRoute: typeof AuthedAppBotRoute
  AuthedAppRoutinesRoute: typeof AuthedAppRoutinesRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppAppsKeyRoute: typeof AuthedAppAppsKeyRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
  AuthedAppAppsIndexRoute: typeof AuthedAppAppsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBotRoute: AuthedAppBotRoute,
  AuthedAppRoutinesRoute: AuthedAppRoutinesRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppAppsKeyRoute: AuthedAppAppsKeyRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
  AuthedAppAppsIndexRoute: AuthedAppAppsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
